FROM ubuntu:16.04
MAINTAINER Brian Gebel <briangeb@gmail.com>

RUN \
  apt-get update && \
  apt-get -y install \
          vim \
          curl \
          git-core && \
  rm -rf /var/lib/apt/lists/*
