version: '3.4'
services:
  dev-base:
    container_name: dev-base
    image: dev-base
    build:
      context: ./dev-base
      dockerfile: Dockerfile
    volumes:
      - $DRIVE_ROOT:/mnt/c
      - "./share:/root/share"
  # dev-box:
  #   container_name: dev-box
  #   hostname: dev.box
  #   image: dev-box
  #   build:
  #     context: ./dev-box
  #     dockerfile: Dockerfile
  #   volumes:
  #     - $USER_WORKSPACE:/mnt/workspace
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - dev-base
  #   tty: true
  dev-docker:
    container_name: dev-docker
    hostname: dev.docker
    image: dev-docker
    build:
      context: ./dev-docker
      dockerfile: Dockerfile
    volumes:
      - $DRIVE_ROOT:/mnt/c
      - "./share:/root/share"
    privileged: true
    ports:
      - "23750:2375"
    depends_on:
      - dev-base
    tty: true
  dev-git:
    container_name: dev-git
    image: dev-git
    build:
      context: ./dev-git
      dockerfile: Dockerfile
    volumes:
      - $DRIVE_ROOT:/mnt/c
      - "./share:/root/share"
    depends_on:
      - dev-base
    tty: true
  dev-php-7.0:
    container_name: dev-php-7.0
    image: dev-php-7.0
    build:
      context: ./dev-php-7.0
      dockerfile: Dockerfile
    ports:
      - "9200:9000"
  dev-php-5.6:
    container_name: dev-php-5.6
    image: dev-php-5.6
    build:
      context: ./dev-php-5.6
      dockerfile: Dockerfile
    ports:
      - "9100:9000"