version: '2.1'
services:
  dev-box:
    container_name: dev-box
    hostname: dev.box
    build:
      context: ./dev-box
      dockerfile: Dockerfile
    volumes:
      - $USER_WORKSPACE:/mnt/workspace
    ports:
      - "8080:8080"
    tty: true
  dev-docker:
    container_name: dev-docker
    image: docker
    privileged: true
    working_dir: "/dkr"
    volumes:
      - ".:/dkr"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: docker ps -a