version: '2.1'
services:
  dev-box:
    container_name: dev-box
    hostname: dev.box
    image: dev-box
    build:
      context: ./dev-box
      dockerfile: Dockerfile
    volumes:
      - $USER_WORKSPACE:/mnt/workspace
    ports:
      - "8080:8080"
    tty: true
  dev-docker:
    container_name: dev-docker
    hostname: dev.docker
    image: dev-docker
    build:
      context: ./dev-docker
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - $DRIVE_ROOT:/c
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "23750:2375"
    tty: true
  dev-git:
    container_name: dev-git
    image: dev-git
    build:
      context: ./dev-git
      dockerfile: Dockerfile
