version: '3.4'
services:
  dev-package-home:
    container_name: dev-package-home
    image: dev-package-home
    build:
      context: ./dev-package-home
      dockerfile: Dockerfile
    volumes:
      - home:/public
  dev-box:
    container_name: dev-box
    hostname: dev.box
    image: dev-box
    build:
      context: ./dev-box
      dockerfile: Dockerfile
    volumes:
      - $USER_WORKSPACE:/mnt/workspace
    ports:
      - "8080:8080"
    depends_on:
      - dev-package-home
    tty: true
  dev-docker:
    container_name: dev-docker
    hostname: dev.docker
    image: dev-docker
    build:
      context: ./dev-docker
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - $DRIVE_ROOT:/mnt/c
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "23750:2375"
    depends_on:
      - dev-package-home
    tty: true
  dev-git:
    container_name: dev-git
    image: dev-git
    build:
      context: ./dev-git
      dockerfile: Dockerfile
    volumes:
      - $DRIVE_ROOT:/mnt/c
      - "./share:/root/share"
    depends_on:
      - dev-package-home
    tty: true
  dev-php-7.0:
    container_name: dev-php-7.0
    image: dev-php-7.0
    build:
      context: ./dev-php-7.0
      dockerfile: Dockerfile
    ports:
      - "9200:9000"
  dev-php-5.6:
    container_name: dev-php-5.6
    image: dev-php-5.6
    build:
      context: ./dev-php-5.6
      dockerfile: Dockerfile
    ports:
      - "9100:9000"
volumes:
    home: