version: '2.1'
services:
  dev-box:
    container_name: dev-box
    hostname: dev.box
    build:
      context: ./dev-box
      dockerfile: Dockerfile
    volumes:
      - $USER_WORKSPACE:/mnt/workspace
    ports:
      - "8080:8080"
    tty: true